---
- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: "{{ repo_uri }}/gpg"
    keyring: "{{ keyring_path }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add HashiCorp repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: "{{ repo_uri }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - main
    signed_by: "{{ keyring_path }}"
  when: ansible_os_family == "Debian"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Hashicorp repository
  ansible.builtin.shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: ansible_os_family == "RedHat"

- name: Install Consul
  ansible.builtin.package:
    name: consul
    state: present

- name: Copy custom consul.hcl configuration file
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: root
    group: root
    mode: "0644"

- name: Copy custom server.hcl configuration file
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/consul.d/server.hcl
    owner: root
    group: root
    mode: "0644"

- name: Create TLS directory if it does not exist
  ansible.builtin.file:
    path: /etc/consul.d/tls
    state: directory
    mode: "0755"
  when: consul_tls_enabled

- name: Copy TLS certificate and key
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/consul.d/tls/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - server.crt
    - server.key
  when: consul_tls_enabled

- name: Copy custom tls.hcl configuration file
  ansible.builtin.template:
    src: tls.hcl.j2
    dest: /etc/consul.d/tls.hcl
    owner: root
    group: root
    mode: "0644"
  when: consul_tls_enabled

- name: Copy shell script for Consul
  ansible.builtin.copy:
    src: consul.sh
    dest: /etc/profile.d/consul.sh
    owner: root
    group: root
    mode: "0755"

- name: Restart Consul
  ansible.builtin.systemd:
    name: consul
    enabled: true
    state: restarted
