---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: truststore
        tasks_from: main.yml
      vars:
        cert_pem: |
          -----BEGIN CERTIFICATE-----
          MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
          ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
          b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
          MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
          b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
          ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
          9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
          IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
          VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
          93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
          jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
          A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
          U5PMCCjjmCXPI6T53iHTfIuJruydjsw2hUwsqdmHyVdRA6SdTyNLQgm8HkmQPsqT
          G+Nn+f1fPLpHfH5Vxs9Q9R88p35PQj6z3sVLReCm8wJqQ0UQUb8+L2h4WFMgGh4y
          lwz8mczz9kjI3XQhLovBc6OYRHdMcqPRa0F2H8LzwzuYpn6+k6+PGHTSjK2nzDNg
          QKhqvx9C95LdJ0CVgWCJHQrRrh2WVPVjXfPEfUk9Lp4bT1m7n4K9rJbqwO1A9z+C
          K5jmJhAiORpNiOx7FNSY4e2h9wGC
          -----END CERTIFICATE-----