---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Install required packages
      ansible.builtin.package:
        name:
          - gnupg
          - python3-debian
          - systemd
        state: present