---
- name: Prepare
  hosts: all
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install required packages
      ansible.builtin.package:
        name:
          - gnupg
          - python3-debian
          - systemd
        state: present
