---
- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: "{{ repo_uri }}/gpg"
    keyring: "{{ keyring_path }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add HashiCorp repository
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: "{{ repo_uri }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - main
    signed_by: "{{ keyring_path }}"
  when: ansible_os_family == "Debian"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Add Hashicorp repository
  ansible.builtin.shell: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: ansible_os_family == "RedHat"

- name: Install Nomad
  ansible.builtin.package:
    name:
      - nomad
      - containernetworking-plugins
    state: present

- name: Copy shell script for Nomad
  ansible.builtin.template:
    src: nomad.sh.j2
    dest: /etc/profile.d/nomad.sh
    owner: root
    group: root
    mode: "0755"

- name: Create nomad configuration directory
  ansible.builtin.file:
    path: /etc/nomad.d
    state: directory
    mode: "0755"

- name: Copy custom nomad.hcl configuration file
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: root
    group: root
    mode: "0644"

- name: Copy custom server.hcl configuration file
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/nomad.d/server.hcl
    owner: root
    group: root
    mode: "0644"
  when: nomad_server_enabled

- name: Copy custom plugins.hcl configuration file
  ansible.builtin.copy:
    src: plugins.hcl
    dest: /etc/nomad.d/plugins.hcl
    owner: root
    group: root
    mode: "0644"

- name: Create TLS directory if it does not exist
  ansible.builtin.file:
    path: /etc/nomad.d/tls
    state: directory
    mode: "0755"
  when: nomad_tls_enabled

- name: Copy TLS certificate and key
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/nomad.d/tls/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - server.crt
    - server.key
  when: nomad_tls_enabled

- name: Copy custom tls.hcl configuration file
  ansible.builtin.template:
    src: tls.hcl.j2
    dest: /etc/nomad.d/tls.hcl
    owner: root
    group: root
    mode: "0644"
  when: nomad_tls_enabled

- name: Restart Nomad
  ansible.builtin.systemd:
    name: nomad
    enabled: true
    state: restarted
