---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ repo_uri }}/{{ ansible_distribution | lower }}/gpg"
    keyring: "{{ keyring_path }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ repo_uri }}/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components:
      - stable
    signed_by: "{{ keyring_path }}"
  when: ansible_os_family == "Debian"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker
  ansible.builtin.package:
    name: docker-ce
    state: present