---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: "{{ repo_uri }}/{{ ansible_distribution | lower }}/gpg"
    keyring: "{{ keyring_path }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ repo_uri }}/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: "{{ release_components }}"
    signed_by: "{{ keyring_path }}"
  when: ansible_os_family == "Debian"

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker packages
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add users to docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users is defined and docker_users | length > 0

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes
  notify: restart docker

- name: Install Docker Compose
  ansible.builtin.get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  when: install_docker_compose | default(true)

- name: Create Docker Compose symlink
  ansible.builtin.file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
  when: install_docker_compose | default(true)

- name: Configure Docker daemon
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker
  when: docker_daemon_config is defined

- name: Create Docker systemd directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  when: docker_systemd_overrides is defined

- name: Configure Docker systemd overrides
  ansible.builtin.template:
    src: docker-override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: '0644'
  notify:
    - reload systemd
    - restart docker
  when: docker_systemd_overrides is defined