---
galaxy_info:
  role_name: truststore
  namespace: blueprint
  author: Blueprint Infrastructure
  description: Manages CA certificates in the system truststore
  company: Blueprint

  license: license (Apache-2.0)

  min_ansible_version: 2.12

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

  galaxy_tags:
    - certificates
    - ca
    - ssl
    - tls
    - security

dependencies: []