name: Image Digest Generation

on:
  workflow_run:
    workflows: ["Sysext Image Manufacturing", "AMI Manufacturing"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  generate:
    env:
      RCLONE_CONFIG_R2_TYPE: s3
      RCLONE_CONFIG_R2_PROVIDER: Cloudflare
      RCLONE_S3_NO_CHECK_BUCKET: true
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - name: ami
            description: Generate digest file for AMI
            precursor: AMI Manufacturing
            prefixes: "raw"
          - name: sysext
            description: Generate digest file for systemd-sysext images
            precursor: Sysext Image Manufacturing
            prefixes: "{qcow2,ova}"
    steps:
      - name: Authenticate to Security Token Service
        uses: narwhl/imprint@v1
        with:
          scope: cloudflare:r2
      - name: Install dependencies
        run: |
          echo "RCLONE_CONFIG_R2_ACCESS_KEY_ID=$CF_R2_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "RCLONE_CONFIG_R2_SECRET_ACCESS_KEY=$CF_R2_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "RCLONE_CONFIG_R2_ENDPOINT=$CF_R2_ENDPOINT_URL" >> $GITHUB_ENV
          sudo apt-get update && sudo apt-get install -yqq rclone
      - name: ${{ matrix.type.description }}
        if: github.event.workflow_run.name == '${{ matrix.type.precursor }}' || github.event_name == 'workflow_dispatch'
        run: |
          rclone copy r2:artifact/${{ matrix.type.name }} . --include "*.${{ matrix.type.prefixes }}"
          sha256sum *.raw | tee SHA256SUMS
          rclone copy SHA256SUMS r2:artifact/${{ matrix.type.name }}/

