name: ""

on:
  push:
    paths:
      - modules/**/*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish terraform modules
    defaults:
      run:
        working-dir: modules
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Gather file changes info
        id: changed
        run: |
          echo "files=$(git diff --name-only HEAD HEAD^)" >> "$GITHUB_OUTPUT"
          echo "directories=$(ls -d)" >> "$GITHUB_OUTPUT"

      - name: Reduce file changes into
        uses: actions/github-script@v7
        with:
          script: | 
            const files = "${{ steps.changed.outputs.files }}".split('\n');
            const moduleDirectories = "${{ steps.changed.outputs.directories }}".split('\n');
            const changedModules = moduleDirectories.filter(moduleDirectory => !files.some(file => file.startsWith(moduleDirectory))
