name: Sysext Image Manufacturing

on:
  push:
    paths:
      - imgfab/sysext/**/*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: imgfab/sysext
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate to Security Token Service
        uses: narwhl/imprint@v1
        with:
          scope: cloudflare:r2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -yqq squashfs-tools rclone
      - name: Packer build
        run: |
          packer build . -parallel-builds=1
